### ISSUE TITLE
Decision state size for disjoint lists is always zero.

### ISSUE THREAD

**Issue by alexzucca90** [dwavesystems/dwave-optimization#127]
This should be different than 0.
```python
from dwave.optimization.model import Model
model = Model()
destinations, routes = model.disjoint_lists(10, 4)
model.decision_state_size()
>>> 0
```

**Comment by arcondello** [comment]
No, because it's instead reported by the `DisjointList` (via inheritance from `ArraySymbol`. And, [due to the way that it's stored under the hood](https://github.com/dwavesystems/dwave-optimization/blob/581649f7d3df90d9169753db6dc94bc44149c541/dwave/optimization/src/nodes/collections.cpp#L536) that count is accurate.

It's an implementation detail that the state is managed by `DisjointLists` rather than the successors.
